---

- name: Check if we need to install Python
  raw: "stat {{ ansible_python_dir }}/.bootstrapped_{{ python_version }}_{{ pypy_version }}"
  register: need_python
  ignore_errors: yes
  changed_when: False

- name: Run install_python.sh
  script: install_python.sh
  environment:
    PYTHON_DIR: "{{ ansible_python_dir }}"
    PYTHON_VERSION: "{{ python_version }}"
    PYPY_VERSION: "{{ pypy_version }}"
  when: need_python is failed


- name: Check if we need to install pip
  shell: "{{ ansible_python_interpreter }} -m pip --version"
  register: need_pip
  ignore_errors: yes
  changed_when: False

- name: Install pip
  shell: "curl https://bootstrap.pypa.io/get-pip.py | {{ ansible_python_interpreter }}"
  args:
    warn: false
  when: need_pip is failed

- name: Install pip launcher
  copy:
    dest: "{{ ansible_python_dir }}/bin/pip"
    mode: 0755
    content: |
      #!/bin/sh
      LD_LIBRARY_PATH={{ ansible_python_dir }}/pypy/lib:$LD_LIBRARY_PATH \
        exec {{ ansible_python_dir }}/pypy/bin/$(basename $0) $@
  when: need_pip is failed
